Security Fix for Cross-site Scripting (XSS)
418sec/dy-server pull request #1
Opened 2021-03-22 15:05 UTC by ritiksahni

### 📊 Metadata *

#### Bounty URL: https://www.huntr.dev/bounties/1-npm-dy-server2

### ⚙️ Description *

An XSS vulnerability was reported in huntr.dev at the link given above.
This was fixed by using a custom function "htmlEncode()" which replaces all the arbitrary characters which were leading to XSS.

### 💻 Technical Description *

The list of files, directories were being displayed and the output was un-sanitized, leading to XSS. After adding a function to replace all the arbitrary characters such as "<", single quotes with HTML encoded text which fixed the vulnerability.

### 🐛 Proof of Concept (PoC) *

1. Start dy-server inside any directory.
2. Inside the directory, place a file or a folder with the name `<img src=x onerror=alert(1)>`
3. Visit the URL for accessing the webpage from dy-server (http://127.0.0.1:8080 by default).

### 🔥 Proof of Fix (PoF) *

Screen recording that shows that XSS vulnerability doesn't exist anymore:
https://drive.google.com/file/d/1OAPNyCKfyadObiJVIrAM34X0Z6WM2tI5/view?usp=sharing

2021-03-22 15:05 UTC, huntr-helper commented
👋 Hello, @RilyZhang. @ritiksahni has opened a PR to us with a fix for a potential vulnerability in your repository. To view the vulnerability, please refer to the bounty URL in the first comment, above. If you want this fix in your repository, a PR will automatically open once you comment:

#### `@huntr-helper - LGTM`

---

#### ☎️ Need further support?

Come and join us on our community [Discord](https://huntr.dev/discord)!

---

#### ❓@RilyZhang - want more fixes like this?

Copy this snippet into your `README.md` for more vulnerability fixes in the future:

```[![huntr](https://cdn.huntr.dev/huntr_security_badge_mono.svg)](https://huntr.dev)```

[![huntr](https://cdn.huntr.dev/huntr_security_badge_mono.svg)](https://huntr.dev)

2021-03-24 07:06 UTC, RilyZhang requested changes
It is right!

2021-03-24 07:13 UTC, JamieSlome commented
@RilyZhang - if you would like this fix in your repository, please write a new comment with the command specified above.

2021-03-26 05:42 UTC, ritiksahni commented
Hi @RilyZhang,

Please tell if you want to merge the fix in your own repository.

2021-03-26 09:08 UTC, RilyZhang approved these changes

2021-03-26 09:25 UTC, JamieSlome commented
@huntr-helper - LGTM

2021-03-26 09:25 UTC, merged